name: lmd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10

  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.1

  - ffmpeg>=6

  - pip
  - git
  - git-lfs
